name: learnova_app
description: A creative student learning and task organizer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/ui/
